<?php

declare(strict_types=1);

namespace Aldavigdis\WpTestsStrapon;

use Aldavigdis\WpTestsStrapon\Defaults;
use Aldavigdis\WpTestsStrapon\FetchWP;

class Config
{
    public string $config_contents;
    public string $wp_version;

    public function __construct(
        string $wp_version = Defaults::WP_VERSION,
        string $wp_default_theme = Defaults::WP_DEFAULT_THEME,
        bool $wp_tests_mutlisite = Defaults::WP_TESTS_MULTISITE,
        bool $wp_debug = Defaults::WP_DEBUG,
        string $table_prefix = Defaults::TABLE_PREFIX,
        string $db_name = Defaults::DB_NAME,
        string $db_user = Defaults::DB_USER,
        string $db_password = Defaults::DB_PASSWORD,
        string $db_host = Defaults::DB_HOST,
        string $wp_tests_domain = Defaults::WP_TESTS_DOMAIN,
        string $wp_tests_email = Defaults::WP_TESTS_EMAIL,
        string $wp_tests_title = Defaults::WP_TESTS_TITLE,
        string $wp_php_binary = Defaults::WP_PHP_BINARY,
        string $wplang = ''
    ) {
        $this->wp_version = getenv('WP_VERSION') ?: $wp_version;

        $this->config_contents = '<?php' . "\n\n";

        $this->config_contents .= $this->formatComment(
            "WordPress test environment configuration file\n\n" .
            "This the configuration file for your WordPress testing environment.\n" .
            "It was automatically generated by the `wp-tests-strapon` package.\n\n" .
            "Feel free to edit it and to commit it to your codebase."
        ) . "\n";

        $this->config_contents .= $this->formatConstant(
            'ABSPATH',
            FetchWP::wpInstallationPath($wp_version),
            'Path to the WordPress codebase you\'d like to test against'
        );

        $this->config_contents .= $this->formatConstant(
            'WP_DEFAULT_THEME',
            getenv('WP_DEFAULT_THEME') ?: $wp_default_theme,
            "Path to the theme to test with"
        );

        $this->config_contents .= $this->formatConstant(
            'WP_TESTS_MULTISITE',
            $wp_tests_mutlisite,
            'Test with multisite enabled'
        );

        $this->config_contents .= $this->formatConstant(
            'WP_DEBUG',
            boolval(getenv('WP_DEBUG')) ?: $wp_debug,
            'Test with WordPress debug mode'
        );

        $this->config_contents .= $this->formatVariable(
            'table_prefix',
            boolval(getenv('TABLE_PREFIX')) ?: $table_prefix,
            null,
            true
        );

        $this->config_contents .= $this->formatConstant(
            'DB_NAME',
            getenv('DB_NAME') ?: $db_name,
            "The database to use for the test\n\n" .
            "Note that all the relevant tables with the above prefix will\n" .
            "be dropped the test suite has run, so don't use the same\n" .
            "database and prefix as your development or production environment."
        );

        $this->config_contents .= $this->formatConstant(
            'DB_USER',
            getenv('DB_USER') ?: $db_user
        );

        $this->config_contents .= $this->formatConstant(
            'DB_PASSWORD',
            getenv('DB_PASSWORD') ?: $db_password
        );

        $this->config_contents .= $this->formatConstant(
            'DB_HOST',
            getenv('DB_HOST') ?: $db_host
        );

        $this->config_contents .= $this->formatConstant(
            'WP_TESTS_DOMAIN',
            getenv('WP_TESTS_DOMAIN') ?: $wp_tests_domain
        );

        $this->config_contents .= $this->formatConstant(
            'WP_TESTS_EMAIL',
            getenv('WP_TESTS_DOMAIN') ?: $wp_tests_email
        );

        $this->config_contents .= $this->formatConstant(
            'WP_TESTS_TITLE',
            getenv('WP_TESTS_TITLE') ?: $wp_tests_title
        );

        $this->config_contents .= $this->formatConstant(
            'WP_PHP_BINARY',
            getenv('WP_PHP_BINARY') ?: $wp_php_binary
        );

        $this->config_contents .= $this->formatConstant(
            'WPLANG',
            getenv('WPLANG') ?: $wplang
        );
    }

    public static function path(): string
    {
        if (defined('WP_TESTS_CONFIG_FILE_PATH') === true) {
            return constant('WP_TESTS_CONFIG_FILE_PATH');
        }

        return sys_get_temp_dir() . "/wp-tests-strapon/config.php";
    }

    public function save()
    {
        if (is_dir(dirname(self::path())) === false) {
            mkdir(dirname(self::path()));
        }

        $file = fopen(self::path(), 'w');
        if (fwrite($file, rtrim($this->config_contents) . "\n")) {
            return true;
        }

        return false;
    }

    private function formatComment(string $comment)
    {
        $comment_lines = explode(PHP_EOL, $comment);
        $entity = '';
        if (is_string($comment)) {
            $entity .= '/**' . "\n";
            foreach ($comment_lines as $c) {
                $trimmed_comment = trim($c);
                $entity .= ' *';
                if (empty($trimmed_comment) === false) {
                    $entity .= ' ' . $trimmed_comment;
                }
                $entity .= "\n";
            }
            $entity .= ' **/' . "\n";
        }
        return $entity;
    }

    private function cleanName(string $name)
    {
        return trim(addslashes(str_replace([' ', '\''], '_', $name)));
    }

    private function cleanValue(string|bool $value)
    {
        if (is_bool($value) === true) {
            if ($value === true) {
                return 'true';
            }
            return 'false';
        }

        return '\'' . trim(addslashes($value)) . '\'';
    }

    private function formatConstant(
        string $name,
        bool|string $value,
        ?string $comment = null
    ) {
        $clean_name  = $this->cleanName($name);
        $clean_value = $this->cleanValue($value);

        $entity = '';
        if (is_string($comment) === true) {
            $entity = $this->formatComment($comment);
        }
        $entity .= "define('$clean_name', $clean_value);\n\n";

        return $entity;
    }

    private function formatVariable(
        string $name,
        string $value,
        ?string $comment = null
    ) {
        $clean_name  = $this->cleanName($name);
        $clean_value = $this->cleanValue($value);

        $entity = '';
        if (is_string($comment) === true) {
            $entity = $this->formatComment($comment);
        }
        $entity .= '$' . "$clean_name = $clean_value;\n\n";

        return $entity;
    }
}
